<section id='footer'>
	<div class="weui-flex">
	  <div class="header-info weui-flex__item">
	  	<div class='footer-select'>
		  	<i class='icon-shouye'></i>
		  	<p>首页</p>
		</div>
	  </div>
	  <div class="header-search weui-flex__item">
	  	<div class='footer-select'>
		  	<i class='icon-wodedingdan'></i>
		  	<p>订单</p>
		</div>
	  </div>
	  <div class="header-search weui-flex__item">
	  	<div class='footer-select'>
		  	<i class='icon-shezhi'></i>
		  	<p>信息</p>
		</div>
	  </div>
	</div>
</section>