<div class='outFood-storeList'>
	<div class="weui-flex storeList-sort">
  		<div class="weui-flex__item active">
  			<span>销量最高</span>
  		</div>
  		<div class="weui-flex__item">
  			<span>评分最高</span>
  		</div>
  		<div class="weui-flex__item">
  			<span>速度最快</span>
  		</div>
  		<div class="weui-flex__item">
  			<span>起送最低</span>
  		</div>
	</div>
	<ul class='menu-list'>
		<li>
			<div class="store-container outFood-container">
		  		<div class="store-perview">
		  			<img src="../images/store-logo/mc.jpg" alt=""/>
		  		</div>
		  		<div class="store-info">
		  			<div class='info-title'><p>麦当劳</p><span>1.4km</span></div>
		  			<div class='info-tag'>
		  				<div class='tag-lt'>
			  				<div class='tag-star'>
			  					<i class='icon-huo active'></i><i class='icon-huo  active'></i><i class='icon-huo  active'></i><i class='icon-huo active'></i><i class='icon-huo active'></i>
			  				</div>
			  				<div class='tag-sales'>月销:<span>1266</span>单</div>
			  			</div>
		  				<div class='tag-gt tag-time'><span>32</span>分钟</div>
		  			</div>
		  			<div class='info-price clearfix'>
		  				<div class='info-start'>起送价:<span>12</span></div>
		  				<div class='info-express'>快递费:<span>12</span></div>
		  			</div>
		  			<div class='info-tele'>
		  				<div><i class='icon-zhaoxiangji'></i></div>
		  				<span>62224913</span>
		  			</div>
		  		</div>
			</div>
		</li>
		<li>
			<div class="store-container outFood-container">
		  		<div class="store-perview">
		  			<img src="../images/store-logo/mc.jpg" alt=""/>
		  		</div>
		  		<div class="store-info">
		  			<div class='info-title'><p>麦当劳</p><span>1.4km</span></div>
		  			<div class='info-tag'>
		  				<div class='tag-lt'>
			  				<div class='tag-star'>
			  					<i class='icon-huo active'></i><i class='icon-huo  active'></i><i class='icon-huo  active'></i><i class='icon-huo active'></i><i class='icon-huo active'></i>
			  				</div>
			  				<div class='tag-sales'>月销:<span>1266</span>单</div>
			  			</div>
		  				<div class='tag-gt tag-time'><span>32</span>分钟</div>
		  			</div>
		  			<div class='info-price clearfix'>
		  				<div class='info-start'>起送价:<span>12</span></div>
		  				<div class='info-express'>快递费:<span>12</span></div>
		  			</div>
		  			<div class='info-tele'>
		  				<div><i class='icon-zhaoxiangji'></i></div>
		  				<span>62224913</span>
		  			</div>
		  		</div>
			</div>
		</li>
		<li>
			<div class="store-container outFood-container">
		  		<div class="store-perview">
		  			<img src="../images/store-logo/mc.jpg" alt=""/>
		  		</div>
		  		<div class="store-info">
		  			<div class='info-title'><p>麦当劳</p><span>1.4km</span></div>
		  			<div class='info-tag'>
		  				<div class='tag-lt'>
			  				<div class='tag-star'>
			  					<i class='icon-huo active'></i><i class='icon-huo  active'></i><i class='icon-huo  active'></i><i class='icon-huo active'></i><i class='icon-huo active'></i>
			  				</div>
			  				<div class='tag-sales'>月销:<span>1266</span>单</div>
			  			</div>
		  				<div class='tag-gt tag-time'><span>32</span>分钟</div>
		  			</div>
		  			<div class='info-price clearfix'>
		  				<div class='info-start'>起送价:<span>12</span></div>
		  				<div class='info-express'>快递费:<span>12</span></div>
		  			</div>
		  			<div class='info-tele'>
		  				<div><i class='icon-zhaoxiangji'></i></div>
		  				<span>62224913</span>
		  			</div>
		  		</div>
			</div>
		</li>
		<li>
			<div class="store-container outFood-container">
		  		<div class="store-perview">
		  			<img src="../images/store-logo/mc.jpg" alt=""/>
		  		</div>
		  		<div class="store-info">
		  			<div class='info-title'><p>麦当劳</p><span>1.4km</span></div>
		  			<div class='info-tag'>
		  				<div class='tag-lt'>
			  				<div class='tag-star'>
			  					<i class='icon-huo active'></i><i class='icon-huo  active'></i><i class='icon-huo  active'></i><i class='icon-huo active'></i><i class='icon-huo active'></i>
			  				</div>
			  				<div class='tag-sales'>月销:<span>1266</span>单</div>
			  			</div>
		  				<div class='tag-gt tag-time'><span>32</span>分钟</div>
		  			</div>
		  			<div class='info-price clearfix'>
		  				<div class='info-start'>起送价:<span>12</span></div>
		  				<div class='info-express'>快递费:<span>12</span></div>
		  			</div>
		  			<div class='info-tele'>
		  				<div><i class='icon-zhaoxiangji'></i></div>
		  				<span>62224913</span>
		  			</div>
		  		</div>
			</div>
		</li>
	</ul>
</div>